const HomeProducts = [
    {
        id:1,
        name: "product1",
        price: '26',
        img: "/images/product1.png",
        category: "",
        type: "new",
    },
    {
        id:2,
        name: "product2",
        price: '96',
        img:"/images/watch.png",
        category: "",
        type: "new",
    },
    {
        id:3,
        name: "product3",
        price: '26',
        img:"/images/watch.png",
        category: "",
        type: "new",
    },
    {
        id:4,
        name: "product4",
        price: '26',
        img:"/images/watch.png",
        category: "",
        type: "featured",
    },
    {
        id:5,
        name: "product5",
        price: '26',
        img:"/images/mobile.png",
        category: "",
        type: "featured",
    },
    {
        id:6,
        name: "product6",
        price: '26',
        img:"/images/watch.png",
        category: "",
        type: "top",
    },
    {
        id:7,
        name: "product7",
        price: '26',
        img:"/images/watch.png",
        category: "",
        type: "top",
    },
    {
        id:8,
        name: "product8",
        price: '26',
        img:"/images/watch.png",
        category: "",
        type: "top",
    },
]
export default HomeProducts