const HomeProducts = [
    {
        id:1,
        name: "product1",
        price: '26',
        img: "/images/product1.png",
        category: "laptop",
        type: "new",
    },
    {
        id:2,
        name: "product2",
        price: '96',
        img:"/images/product2.png",
        category: "laptop",
        type: "new",
    },
    {
        id:3,
        name: "product3",
        price: '26',
        img:"/images/product3.png",
        category: "watch",
        type: "new",
    },
    {
        id:4,
        name: "product4",
        price: '26',
        img:"/images/product4.png",
        category: "mobile",
        type: "featured",
    },
    {
        id:5,
        name: "product5",
        price: '26',
        img:"/images/product5.png",
        category: "speaker",
        type: "featured",
    },
    {
        id:6,
        name: "product6",
        price: '26',
        img:"/images/product6.png",
        category: "headphones",
        type: "top",
    },
    {
        id:7,
        name: "product7",
        price: '26',
        img:"/images/product7.png",
        category: "headphones",
        type: "top",
    },
    {
        id:8,
        name: "product8",
        price: '26',
        img:"/images/product8.png",
        category: "tv",
        type: "top",
    },
    {
        id:9,
        name: "product9",
        price: '26',
        img: "/images/product9.png",
        category: "mobile",
        type: "new",
    },
    {
        id:10,
        name: "product10",
        price: '26',
        img:"/images/product10.png",
        category: "tv",
        type: "featured",
    },
    {
        id:11,
        name: "product11",
        price: '26',
        img:"/images/product11.png",
        category: "speaker",
        type: "featured",
    },
    {
        id:12,
        name: "product12",
        price: '26',
        img:"/images/product12.png",
        category: "watch",
        type: "top",
    },
    
]
export default HomeProducts